[2024-08-25T00:00:27.974+0000] {processor.py:186} INFO - Started process (PID=38561) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:00:27.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:00:27.991+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:00:27.990+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:00:28.046+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:00:28.031+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:00:28.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:00:28.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.189 seconds
[2024-08-25T00:05:41.715+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:05:41.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:05:41.743+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:05:41.742+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:05:41.864+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:05:41.807+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:05:41.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:05:42.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.520 seconds
[2024-08-25T00:06:12.526+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:06:12.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:06:12.556+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:06:12.549+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:06:12.706+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:06:12.687+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:06:12.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:06:12.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.348 seconds
[2024-08-25T00:06:45.103+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:06:45.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:06:45.151+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:06:45.142+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:06:45.450+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:06:45.383+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:06:45.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:06:45.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.628 seconds
[2024-08-25T00:07:20.524+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:07:20.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:07:20.539+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:07:20.538+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:07:20.589+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:07:20.580+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:07:20.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:07:20.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.152 seconds
[2024-08-25T00:07:51.557+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:07:51.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:07:51.569+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:07:51.568+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:07:51.624+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:07:51.602+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:07:51.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:07:51.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.200 seconds
[2024-08-25T00:08:22.557+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:08:22.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:08:22.584+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:08:22.583+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:08:22.760+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:08:22.740+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:08:22.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:08:22.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.492 seconds
[2024-08-25T00:08:53.723+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:08:53.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:08:53.730+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:08:53.729+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:08:53.768+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:08:53.759+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:08:53.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:08:53.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.133 seconds
[2024-08-25T00:09:24.551+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:09:24.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:09:24.560+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:09:24.559+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:09:24.594+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:09:24.587+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:09:24.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:09:24.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.138 seconds
[2024-08-25T00:09:55.821+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:09:55.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:09:55.829+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:09:55.828+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:09:55.926+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:09:55.856+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:09:55.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:09:56.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.244 seconds
[2024-08-25T00:10:27.593+0000] {processor.py:186} INFO - Started process (PID=595) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:10:27.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:10:27.611+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:10:27.610+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:10:28.656+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:10:27.668+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:10:28.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:10:28.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 1.285 seconds
[2024-08-25T00:11:00.707+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:11:00.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:11:00.717+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:11:00.716+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:11:00.752+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:11:00.744+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:11:00.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:11:00.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.131 seconds
[2024-08-25T00:11:31.293+0000] {processor.py:186} INFO - Started process (PID=724) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:11:31.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:11:31.301+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:11:31.300+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:11:31.330+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:11:31.322+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:11:31.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:11:31.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.100 seconds
[2024-08-25T00:12:03.241+0000] {processor.py:186} INFO - Started process (PID=788) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:12:03.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:12:03.247+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:12:03.246+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:12:03.275+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:12:03.267+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:12:03.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:12:03.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.096 seconds
[2024-08-25T00:12:33.782+0000] {processor.py:186} INFO - Started process (PID=851) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:12:33.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:12:33.791+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:12:33.790+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:12:33.822+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:12:33.814+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:12:33.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:12:33.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.118 seconds
[2024-08-25T00:13:04.199+0000] {processor.py:186} INFO - Started process (PID=907) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:13:04.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:13:04.210+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:13:04.209+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:13:04.247+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:13:04.238+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:13:04.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:13:04.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.123 seconds
[2024-08-25T00:13:35.128+0000] {processor.py:186} INFO - Started process (PID=970) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:13:35.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:13:35.136+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:13:35.135+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:13:35.170+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:13:35.163+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:13:35.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:13:35.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.130 seconds
[2024-08-25T00:14:05.684+0000] {processor.py:186} INFO - Started process (PID=1033) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:14:05.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:14:05.692+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:14:05.691+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:14:05.723+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:14:05.717+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:14:05.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:14:05.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.102 seconds
[2024-08-25T00:14:37.048+0000] {processor.py:186} INFO - Started process (PID=1097) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:14:37.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:14:37.064+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:14:37.063+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:14:37.116+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:14:37.100+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:14:37.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:14:37.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.164 seconds
[2024-08-25T00:15:08.025+0000] {processor.py:186} INFO - Started process (PID=1159) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:15:08.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:15:08.038+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:15:08.036+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:15:08.107+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:15:08.095+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:15:08.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:15:08.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.187 seconds
[2024-08-25T00:15:38.290+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:15:38.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:15:38.297+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:15:38.296+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:15:38.335+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:15:38.325+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:15:38.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:15:38.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.118 seconds
[2024-08-25T00:16:08.620+0000] {processor.py:186} INFO - Started process (PID=1280) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:16:08.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:16:08.629+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:16:08.628+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:16:08.691+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:16:08.676+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:16:08.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:16:08.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.153 seconds
[2024-08-25T00:16:39.684+0000] {processor.py:186} INFO - Started process (PID=1342) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:16:39.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:16:39.699+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:16:39.699+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:16:39.804+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:16:39.782+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:16:39.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:16:39.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.315 seconds
[2024-08-25T00:17:12.575+0000] {processor.py:186} INFO - Started process (PID=1404) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:17:12.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:17:12.757+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:17:12.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:17:13.638+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:17:13.471+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:17:13.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:17:14.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 1.622 seconds
[2024-08-25T00:17:44.942+0000] {processor.py:186} INFO - Started process (PID=1467) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:17:44.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:17:44.949+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:17:44.949+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:17:45.094+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:17:45.049+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:17:45.100+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:17:45.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.273 seconds
[2024-08-25T00:18:16.088+0000] {processor.py:186} INFO - Started process (PID=1530) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:18:16.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:18:16.096+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:18:16.095+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:18:16.127+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:18:16.120+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:18:16.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:18:16.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.125 seconds
[2024-08-25T00:18:46.850+0000] {processor.py:186} INFO - Started process (PID=1592) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:18:46.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:18:46.861+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:18:46.860+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:18:46.924+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:18:46.913+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:18:46.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:18:46.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.156 seconds
[2024-08-25T00:19:17.546+0000] {processor.py:186} INFO - Started process (PID=1655) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:19:17.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:19:17.591+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:19:17.589+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:19:17.629+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:19:17.622+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:19:17.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:19:17.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.192 seconds
[2024-08-25T00:19:47.979+0000] {processor.py:186} INFO - Started process (PID=1717) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:19:47.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:19:47.993+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:19:47.992+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:19:48.060+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:19:48.042+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:19:48.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:19:48.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.417 seconds
[2024-08-25T00:20:18.876+0000] {processor.py:186} INFO - Started process (PID=1781) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:20:18.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:20:18.884+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:20:18.883+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:20:18.915+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:20:18.908+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:20:18.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:20:18.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.133 seconds
[2024-08-25T00:20:49.526+0000] {processor.py:186} INFO - Started process (PID=1843) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:20:49.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:20:49.533+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:20:49.532+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:20:49.560+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:20:49.552+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:20:49.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:20:49.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.093 seconds
[2024-08-25T00:26:14.651+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:26:14.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:26:14.669+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:26:14.668+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:26:14.736+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:26:14.720+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:26:14.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:26:14.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.424 seconds
[2024-08-25T00:27:18.822+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:27:18.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:27:18.863+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:27:18.862+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:27:19.046+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:27:18.990+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:27:19.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:27:19.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.596 seconds
[2024-08-25T00:28:05.143+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:28:05.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:28:05.241+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:28:05.240+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:28:05.686+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:28:05.649+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:28:05.711+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:28:05.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.767 seconds
[2024-08-25T00:28:37.006+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:28:37.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:28:37.045+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:28:37.044+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:28:37.431+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:28:37.412+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:28:37.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:28:37.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.626 seconds
[2024-08-25T00:29:08.992+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:29:08.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:29:09.008+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:29:09.006+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:29:09.116+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:29:09.093+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:29:09.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:29:09.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.384 seconds
[2024-08-25T00:29:39.966+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:29:39.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:29:39.977+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:29:39.976+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:29:40.078+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:29:40.061+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:29:40.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:29:40.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.236 seconds
[2024-08-25T00:30:13.246+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:30:13.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:30:13.265+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:30:13.264+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:30:14.221+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:30:14.153+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:30:14.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:30:14.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 1.163 seconds
[2024-08-25T00:30:45.262+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:30:45.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:30:45.269+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:30:45.269+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:30:45.300+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:30:45.293+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:30:45.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:30:45.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.103 seconds
[2024-08-25T00:31:18.833+0000] {processor.py:186} INFO - Started process (PID=562) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:31:18.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:31:18.907+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:31:18.906+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:31:20.584+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:31:20.428+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:31:20.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:31:21.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 2.988 seconds
[2024-08-25T00:32:09.123+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:32:09.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:32:09.133+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:32:09.132+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:32:09.190+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:32:09.174+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:32:09.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:32:09.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.207 seconds
[2024-08-25T00:32:40.937+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:32:40.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:32:41.002+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:32:41.001+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:32:41.690+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:32:41.638+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:32:41.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:32:41.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.983 seconds
[2024-08-25T00:33:22.125+0000] {processor.py:186} INFO - Started process (PID=739) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:33:22.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:33:22.167+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:33:22.166+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:33:22.354+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:33:22.330+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:33:22.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:33:22.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.354 seconds
[2024-08-25T00:33:53.787+0000] {processor.py:186} INFO - Started process (PID=772) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:33:53.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:33:53.855+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:33:53.855+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:33:54.148+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:33:54.107+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:33:54.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:33:54.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.673 seconds
[2024-08-25T00:34:24.841+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:34:24.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:34:24.865+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:34:24.864+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:34:24.915+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:34:24.903+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:34:24.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:34:25.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.231 seconds
[2024-08-25T00:34:55.697+0000] {processor.py:186} INFO - Started process (PID=898) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:34:55.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:34:55.705+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:34:55.704+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:34:55.748+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:34:55.736+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:34:55.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:34:55.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.130 seconds
[2024-08-25T00:35:31.929+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:35:31.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:35:31.950+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:35:31.949+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:35:32.119+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:35:32.065+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:35:32.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:35:32.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.436 seconds
[2024-08-25T00:36:06.252+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:36:06.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:36:06.266+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:36:06.262+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:36:06.311+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:36:06.303+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:36:06.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:36:06.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.155 seconds
[2024-08-25T00:36:36.591+0000] {processor.py:186} INFO - Started process (PID=1075) to work on /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:36:36.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_parquet_e_lotes.py for tasks to queue
[2024-08-25T00:36:36.602+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:36:36.601+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:36:36.639+0000] {logging_mixin.py:190} INFO - [2024-08-25T00:36:36.630+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_parquet_e_lotes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_parquet_e_lotes.py", line 8, in <module>
    from astro import sql as aql
ModuleNotFoundError: No module named 'astro'
[2024-08-25T00:36:36.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_parquet_e_lotes.py
[2024-08-25T00:36:36.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_parquet_e_lotes.py took 0.167 seconds
